[project]
name = 'fakfun-preorder'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 3
epoch = 'latest'

[contracts.t-shirt-faktory]
path = 'contracts/t-shirt-faktory.clar'
clarity_version = 3
epoch = '3.2'

[contracts.usda-token]
path = 'contracts/usda-token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
